DirectCRonDirect
SciML/DiffEqJump.jl pull request #197
Opened 2021-07-31 00:04 UTC by Vilin97

Implemented `DirectCRonDirect` -- a spatial SSA that chooses the site with the composition-rejection search and chooses the reaction or hop via linear search (Direct method).

2021-08-03 20:02 UTC, isaacsas requested changes

2021-08-03 21:21 UTC, Vilin97 commented on src/spatial/DirectCRonDirect.jl
> +    rt = PriorityTable(ratetogroup, zeros(T, num_sites(spatial_system)), minrate, 2*minrate)
Yes, I had forgotten to make these changes in the spatial DirectCR

2021-08-03 21:22 UTC, Vilin97 commented on src/spatial/DirectCRonDirect.jl
> +function initialize!(p::DirectCRonDirectJumpAggregation, integrator, u, params, t)
Yes. I can move it out to `initialize!` if you think it makes more sense.

2021-08-03 21:31 UTC, Vilin97 commented on src/spatial/DirectCRonDirect.jl
> +        if rand(rng)*(total_site_rate(rx_rates, hop_rates, site)) < total_site_rx_rate(rx_rates, site)
Yes, done. Good idea.

2021-08-03 21:44 UTC, Vilin97 commented on src/spatial/DirectCRonDirect.jl
> +    num_sites = DiffEqJump.num_sites(spatial_system)
For some reason my REPL sometimes complaints about it when there is no `DiffEqJump` at front

2021-08-03 23:48 UTC, isaacsas requested changes

2021-08-03 23:48 UTC, isaacsas commented on src/spatial/DirectCRDirect.jl
> +    num_rxs = num_rxs(rx_rates)
Rename these local variables.

2021-08-03 23:48 UTC, isaacsas commented on src/spatial/DirectCRonDirect.jl
> +function initialize!(p::DirectCRonDirectJumpAggregation, integrator, u, params, t)
No it’s fine, just checking.

2021-08-03 23:50 UTC, isaacsas commented on src/spatial/DirectCRonDirect.jl
> +    p.next_jump = sample_jump_direct(p, site)
Maybe call this something like `sample_jump_at_site_direct`?

2021-08-03 23:50 UTC, isaacsas commented on src/spatial/DirectCRonDirect.jl
> +    p.next_jump = sample_jump_direct(p, site)
Actually the `direct` isn’t needed; other appraoches could use the same function and just dispatch (like RSSA).

2021-08-04 01:07 UTC, isaacsas approved these changes

2021-08-04 01:33 UTC, merged